//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserClient.Properties.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : ähnelt.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /Downloads ähnelt.
        /// </summary>
        internal static string Directory_Downloads {
            get {
                return ResourceManager.GetString("Directory_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Download ist ein Fehler aufgetreten. Eines Ihrer Datenpakete konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string ErrorWhileDownload {
            get {
                return ResourceManager.GetString("ErrorWhileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .png ähnelt.
        /// </summary>
        internal static string ExtensionPNG {
            get {
                return ResourceManager.GetString("ExtensionPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die savedfiles.xml ähnelt.
        /// </summary>
        internal static string File_SavedFilesXML {
            get {
                return ResourceManager.GetString("File_SavedFilesXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die networkinfo.xml ähnelt.
        /// </summary>
        internal static string NetworkInfoFileName {
            get {
                return ResourceManager.GetString("NetworkInfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Error:  ähnelt.
        /// </summary>
        internal static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben noch keine Datein im Netzwerkgespeichert. ähnelt.
        /// </summary>
        internal static string Output_NoSavedFiles {
            get {
                return ResourceManager.GetString("Output_NoSavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei  ähnelt.
        /// </summary>
        internal static string Output_ReplaceFile1 {
            get {
                return ResourceManager.GetString("Output_ReplaceFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  existiert bereits. Möchten Sie sie ersetzen? ähnelt.
        /// </summary>
        internal static string Output_ReplaceFile2 {
            get {
                return ResourceManager.GetString("Output_ReplaceFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei bereits vorhanden ähnelt.
        /// </summary>
        internal static string Output_ReplaceFileTitle {
            get {
                return ResourceManager.GetString("Output_ReplaceFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requested file was not found. ähnelt.
        /// </summary>
        internal static string ReqFileNotFound {
            get {
                return ResourceManager.GetString("ReqFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requested fragment had invalid hash. ähnelt.
        /// </summary>
        internal static string ReqFragInvalidHash {
            get {
                return ResourceManager.GetString("ReqFragInvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requested fragment was not found. ähnelt.
        /// </summary>
        internal static string ReqFragNotFound {
            get {
                return ResourceManager.GetString("ReqFragNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One of fragments of the requested file was not found. ähnelt.
        /// </summary>
        internal static string ReqFragOneNotFound {
            get {
                return ResourceManager.GetString("ReqFragOneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Torrentserver had internal error when fragment was requested. ähnelt.
        /// </summary>
        internal static string ReqInternalError {
            get {
                return ResourceManager.GetString("ReqInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die savedfiles.xml ähnelt.
        /// </summary>
        internal static string SavedFilesInfoFileName {
            get {
                return ResourceManager.GetString("SavedFilesInfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ;  ähnelt.
        /// </summary>
        internal static string SemiColon {
            get {
                return ResourceManager.GetString("SemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die / ähnelt.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
    }
}
