module TrackerServer
{
	struct NetworkInfo
	{
		long fragmentSize;
		sequence<string> torrentServer;
	};

	struct FragmentInfo
	{
		long sequenceNumber;
		string fragmentHash;
		string fileHash;
	};

	struct FileInfo
	{
		long size;
		string hash;
	};

	typedef sequence<char> Data;

	enum UploadStatus { Initiated, Pending, Canceled, Validating, Distributing, Distributed };

	interface ITrackerServer
	{
		NetworkInfo GetNetworkInfo();
		UploadStatus GetUploadStatus(in string fileHash);
		void InitiateUpload(in long size, in string hash);
		void UploadFragment(in FragmentInfo info, in Data fragment);
	};
};
