package TrackerServer;

/**
* TrackerServer/FileInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class FileInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public TrackerServer.FileInfo value = null;

  public FileInfoHolder ()
  {
  }

  public FileInfoHolder (TrackerServer.FileInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrackerServer.FileInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrackerServer.FileInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrackerServer.FileInfoHelper.type ();
  }

}
