package TrackerServer;


/**
* TrackerServer/FragmentInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class FragmentInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int sequenceNumber = (int)0;
  public String fragmentHash = null;
  public String fileHash = null;

  public FragmentInfo ()
  {
  } // ctor

  public FragmentInfo (int _sequenceNumber, String _fragmentHash, String _fileHash)
  {
    sequenceNumber = _sequenceNumber;
    fragmentHash = _fragmentHash;
    fileHash = _fileHash;
  } // ctor

} // class FragmentInfo
