package TrackerServer;

/**
* TrackerServer/FragmentInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class FragmentInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public TrackerServer.FragmentInfo value = null;

  public FragmentInfoHolder ()
  {
  }

  public FragmentInfoHolder (TrackerServer.FragmentInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrackerServer.FragmentInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrackerServer.FragmentInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrackerServer.FragmentInfoHelper.type ();
  }

}
