package TrackerServer;

/**
* TrackerServer/ITrackerServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class ITrackerServerHolder implements org.omg.CORBA.portable.Streamable
{
  public TrackerServer.ITrackerServer value = null;

  public ITrackerServerHolder ()
  {
  }

  public ITrackerServerHolder (TrackerServer.ITrackerServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrackerServer.ITrackerServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrackerServer.ITrackerServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrackerServer.ITrackerServerHelper.type ();
  }

}
