package TrackerServer;


/**
* TrackerServer/NetworkInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class NetworkInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int fragmentSize = (int)0;
  public String torrentServer[] = null;

  public NetworkInfo ()
  {
  } // ctor

  public NetworkInfo (int _fragmentSize, String[] _torrentServer)
  {
    fragmentSize = _fragmentSize;
    torrentServer = _torrentServer;
  } // ctor

} // class NetworkInfo
