package TrackerServer;

/**
* TrackerServer/UploadStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public final class UploadStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public TrackerServer.UploadStatus value = null;

  public UploadStatusHolder ()
  {
  }

  public UploadStatusHolder (TrackerServer.UploadStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrackerServer.UploadStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrackerServer.UploadStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrackerServer.UploadStatusHelper.type ();
  }

}
