package TrackerServer;


/**
* TrackerServer/UploadStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyTorrent.idl
* Mittwoch, 8. Januar 2020 15:41 Uhr MEZ
*/

public class UploadStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static TrackerServer.UploadStatus[] __array = new TrackerServer.UploadStatus [__size];

  public static final int _Initiated = 0;
  public static final TrackerServer.UploadStatus Initiated = new TrackerServer.UploadStatus(_Initiated);
  public static final int _Pending = 1;
  public static final TrackerServer.UploadStatus Pending = new TrackerServer.UploadStatus(_Pending);
  public static final int _Canceled = 2;
  public static final TrackerServer.UploadStatus Canceled = new TrackerServer.UploadStatus(_Canceled);
  public static final int _Validating = 3;
  public static final TrackerServer.UploadStatus Validating = new TrackerServer.UploadStatus(_Validating);
  public static final int _Distributing = 4;
  public static final TrackerServer.UploadStatus Distributing = new TrackerServer.UploadStatus(_Distributing);
  public static final int _Distributed = 5;
  public static final TrackerServer.UploadStatus Distributed = new TrackerServer.UploadStatus(_Distributed);

  public int value ()
  {
    return __value;
  }

  public static TrackerServer.UploadStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected UploadStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class UploadStatus
